topic_list = [
    None,
    "Pacific Time (US & Canada)",
    "Eastern Time (US & Canada)",
    "Central Time (US & Canada)",
    "Brasilia",
    "London",
    "Amsterdam",
    "Athens",
    "Atlantic Time (Canada)",
    "Quito",
    "Buenos Aires",
    "Santiago",
    "Paris",
    "Hawaii",
    "Baghdad",
    "Istanbul",
    "Arizona",
    "Madrid",
    "Mountain Time (US & Canada)",
    "Kyiv",
    "Riyadh",
    "Tokyo",
    "Greenland",
    "Casablanca",
    "Ljubljana",
    "Belgrade",
    "Caracas",
    "Lisbon",
    "Mid-Atlantic",
    "Mexico City",
    "Cairo",
    "Jakarta",
    "Irkutsk",
    "Bogota",
    "Rome",
    "Bangkok",
    "Dublin",
    "Abu Dhabi",
    "Seoul",
    "Alaska",
    "Bern",
    "Berlin",
    "Central America",
    "New Delhi",
    "Beijing",
    "Bucharest",
    "Hanoi",
    "West Central Africa",
    "Minsk",
    "Kuwait",
    "Chennai",
    "Pretoria",
    "Tijuana",
    "Warsaw",
    "Urumqi",
    "Osaka",
    "Helsinki",
    "Kuala Lumpur",
    "Moscow",
    "Singapore",
    "Indiana (East)",
    "Brussels",
    "Karachi",
    "Stockholm",
    "International Date Line West",
    "Volgograd",
    "Hong Kong",
    "Georgetown",
    "Edinburgh",
    "Sarajevo",
    "America/Montevideo",
    "St. Petersburg",
    "Monterrey",
    "Yerevan",
    "Monrovia",
    "Mumbai",
    "America/Detroit",
    "Almaty",
    "Chihuahua",
    "Asia/Tehran",
    "Nairobi",
    "Krasnoyarsk",
    "Islamabad",
    "Midway Island",
    "Riga",
    "Europe/London",
    "Europe/Athens",
    "Guadalajara",
    "Prague",
    "Melbourne",
    "La Paz",
    "America/Chicago",
    "Muscat",
    "Ekaterinburg",
    "Copenhagen",
    "Asia/Singapore",
    "America/Guayaquil",
    "America/Guatemala",
    "Vienna",
    "Asia/Tokyo",
    "Tehran",
    "America/New_York",
    "IST",
    "Skopje",
    "Mazatlan",
    "Europe/Istanbul",
    "America/Argentina/Buenos_Aires",
    "BST",
    "Jerusalem",
    "Europe/Madrid",
    "Lima",
    "Asia/Riyadh",
    "Brisbane",
    "Azores",
    "Baku",
    "Novosibirsk",
    "Bratislava",
    "Ulaan Bataar",
    "JST"
]

def get_topic_list() -> list:
    return topic_list
